from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(460, 550)
        MainWindow.setMinimumSize(QtCore.QSize(460, 550))
        MainWindow.setMaximumSize(QtCore.QSize(460, 550))
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 462, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self._0 = QtWidgets.QPushButton(self.centralwidget)
        self._0.setGeometry(QtCore.QRect(130, 440, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._0.setFont(font)
        self._0.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._0.setObjectName("_0")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(20, 440, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dot.setFont(font)
        self.dot.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                               "background-color: rgb(193, 204, 187);")
        self.dot.setObjectName("dot")
        self._1 = QtWidgets.QPushButton(self.centralwidget)
        self._1.setGeometry(QtCore.QRect(20, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._1.setFont(font)
        self._1.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._1.setObjectName("_1")
        self._2 = QtWidgets.QPushButton(self.centralwidget)
        self._2.setGeometry(QtCore.QRect(130, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._2.setFont(font)
        self._2.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._2.setObjectName("_2")
        self._3 = QtWidgets.QPushButton(self.centralwidget)
        self._3.setGeometry(QtCore.QRect(240, 330, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._3.setFont(font)
        self._3.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._3.setObjectName("_3")
        self._4 = QtWidgets.QPushButton(self.centralwidget)
        self._4.setGeometry(QtCore.QRect(20, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._4.setFont(font)
        self._4.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._4.setObjectName("_4")
        self._5 = QtWidgets.QPushButton(self.centralwidget)
        self._5.setGeometry(QtCore.QRect(130, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._5.setFont(font)
        self._5.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._5.setObjectName("_5")
        self._6 = QtWidgets.QPushButton(self.centralwidget)
        self._6.setGeometry(QtCore.QRect(240, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._6.setFont(font)
        self._6.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._6.setObjectName("_6")
        self._7 = QtWidgets.QPushButton(self.centralwidget)
        self._7.setGeometry(QtCore.QRect(20, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._7.setFont(font)
        self._7.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._7.setObjectName("_7")
        self._8 = QtWidgets.QPushButton(self.centralwidget)
        self._8.setGeometry(QtCore.QRect(130, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._8.setFont(font)
        self._8.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._8.setObjectName("_8")
        self._9 = QtWidgets.QPushButton(self.centralwidget)
        self._9.setGeometry(QtCore.QRect(240, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._9.setFont(font)
        self._9.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                              "background-color: rgb(193, 204, 187);")
        self._9.setObjectName("_9")
        self._x10 = QtWidgets.QPushButton(self.centralwidget)
        self._x10.setGeometry(QtCore.QRect(240, 440, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._x10.setFont(font)
        self._x10.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                "background-color: rgb(193, 204, 187);")
        self._x10.setObjectName("_x10")
        self._plus = QtWidgets.QPushButton(self.centralwidget)
        self._plus.setGeometry(QtCore.QRect(370, 110, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._plus.setFont(font)
        self._plus.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                 "background-color: rgb(255, 129, 131);")
        self._plus.setObjectName("_plus")
        self._minus = QtWidgets.QPushButton(self.centralwidget)
        self._minus.setGeometry(QtCore.QRect(370, 180, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._minus.setFont(font)
        self._minus.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                  "background-color: rgb(255, 129, 131);")
        self._minus.setObjectName("_minus")
        self._divide = QtWidgets.QPushButton(self.centralwidget)
        self._divide.setGeometry(QtCore.QRect(370, 320, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._divide.setFont(font)
        self._divide.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                   "background-color: rgb(255, 129, 131);")
        self._divide.setObjectName("_divide")
        self._times = QtWidgets.QPushButton(self.centralwidget)
        self._times.setGeometry(QtCore.QRect(370, 250, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._times.setFont(font)
        self._times.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                  "background-color: rgb(255, 129, 131);")
        self._times.setObjectName("_times")
        self._bracketleft = QtWidgets.QPushButton(self.centralwidget)
        self._bracketleft.setGeometry(QtCore.QRect(340, 390, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._bracketleft.setFont(font)
        self._bracketleft.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                        "background-color: rgb(255, 255, 165);")
        self._bracketleft.setObjectName("_bracketleft")
        self._bracketright = QtWidgets.QPushButton(self.centralwidget)
        self._bracketright.setGeometry(QtCore.QRect(400, 390, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._bracketright.setFont(font)
        self._bracketright.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                         "background-color: rgb(255, 255, 165);")
        self._bracketright.setObjectName("_bracketright")
        self._equal = QtWidgets.QPushButton(self.centralwidget)
        self._equal.setGeometry(QtCore.QRect(340, 450, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self._equal.setFont(font)
        self._equal.setStyleSheet("border-color: rgb(48, 48, 48);\n"
                                  "background-color: rgb(255, 151, 255);")
        self._equal.setObjectName("_equal")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 2, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                 "background-color: rgb(221, 221, 221);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.x = ""
        self._0.pressed.connect(lambda: self._print("0"))
        self._1.pressed.connect(lambda: self._print("1"))
        self._2.pressed.connect(lambda: self._print("2"))
        self._3.pressed.connect(lambda: self._print("3"))
        self._4.pressed.connect(lambda: self._print("4"))
        self._5.pressed.connect(lambda: self._print("5"))
        self._6.pressed.connect(lambda: self._print("6"))
        self._7.pressed.connect(lambda: self._print("7"))
        self._8.pressed.connect(lambda: self._print("8"))
        self._9.pressed.connect(lambda: self._print("9"))
        self._plus.pressed.connect(lambda: self._print("+"))
        self._minus.pressed.connect(lambda: self._print("-"))
        self.dot.pressed.connect(lambda: self._print("."))
        self._divide.pressed.connect(lambda: self._print("/"))
        self._bracketleft.pressed.connect(lambda: self._print("("))
        self._bracketright.pressed.connect(lambda: self._print(")"))
        self._x10.pressed.connect(lambda: self._print("*10"))
        self._times.pressed.connect(lambda: self._print("*"))
        self._equal.pressed.connect(self.calculate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator "))
        MainWindow.setWindowIcon(QtGui.QIcon("xy.ico"))
        self._0.setText(_translate("MainWindow", "0"))
        self.dot.setText(_translate("MainWindow", "."))
        self._1.setText(_translate("MainWindow", "1"))
        self._2.setText(_translate("MainWindow", "2"))
        self._3.setText(_translate("MainWindow", "3"))
        self._4.setText(_translate("MainWindow", "4"))
        self._5.setText(_translate("MainWindow", "5"))
        self._6.setText(_translate("MainWindow", "6"))
        self._7.setText(_translate("MainWindow", "7"))
        self._8.setText(_translate("MainWindow", "8"))
        self._9.setText(_translate("MainWindow", "9"))
        self._x10.setText(_translate("MainWindow", "*10"))
        self._plus.setText(_translate("MainWindow", "+"))
        self._minus.setText(_translate("MainWindow", "-"))
        self._divide.setText(_translate("MainWindow", "/"))
        self._times.setText(_translate("MainWindow", "x"))
        self._bracketleft.setText(_translate("MainWindow", "("))
        self._bracketright.setText(_translate("MainWindow", ")"))
        self._equal.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "Designed by Mohamed Emad"))



    def calculate(self):
        y = self.lineEdit.text()
        _sum = eval(y)
        self.lineEdit.setText(y + " = " + str(_sum))
        self.x = ""

    def _print(self, i):
        self.x += i
        self.lineEdit.setText(self.x)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
